name: acceptance-tests
on:
  pull_request_target:
    branches:
      - main
      - release-*

env:
  GRADLE_OPTS: "-Xmx6g -Dorg.gradle.daemon=false"
  total-runners: 16

jobs:
  authorize:
    environment:
      ${{ github.event_name == 'pull_request_target' &&
      github.event.pull_request.head.repo.full_name != github.repository &&
      'external' || 'internal' }}
    runs-on: ubuntu-22.04
    steps:
      - run: true

  acceptanceTestEthereum:
    runs-on: ubuntu-22.04
    name: "Acceptance Runner"
    needs: authorize
    permissions:
      statuses: write
      checks: write
    strategy:
      fail-fast: true
      matrix:
        runner_index: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
      - name: Set up Java
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93
        with:
          distribution: temurin
          java-version: 17
      - name: get acceptance test report
        uses: dawidd6/action-download-artifact@e7466d1a7587ed14867642c2ca74b5bcc1e19a2d
        with:
          branch: main
          name_is_regexp: true
          name: 'acceptance-node-\d*\d-test-results'
          path: tmp/junit-xml-reports-downloaded
          if_no_artifact_found: true
      - name: setup gradle
        uses: gradle/gradle-build-action@a8f75513eafdebd8141bd1cd4e30fcd194af8dfa
      - name: Split tests
        id: split-tests
        uses: r7kamura/split-tests-by-timings@9322bd292d9423e2bc5a65bec548901801341e3f
        with:
          reports: tmp/junit-xml-reports-downloaded
          glob: 'acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/**/*Test.java'
          total: ${{env.total-runners}}
          index: ${{ matrix.runner_index }}
      - name: write out test list
        run: echo "${{ steps.split-tests.outputs.paths }}" >> testList.txt
      - name: format gradle args
        #regex means: first truncate file paths to align with package name, then swap path delimiter with package delimiter,
        #then drop file extension, then insert --tests option between each.
        run: cat testList.txt | sed -e 's@acceptance-tests/tests/src/test/java/@--tests\ @g;s@/@.@g;s/\.java//g'  > gradleArgs.txt
      - name: run acceptance tests
        run: ./gradlew acceptanceTest `cat gradleArgs.txt` -Dorg.gradle.parallel=true -Dorg.gradle.caching=true
      - name: cleanup tempfiles
        run: rm testList.txt gradleArgs.txt
      - name: Upload Acceptance Test Results
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32
        with:
          name: acceptance-node-${{matrix.runner_index}}-test-results
          path: 'acceptance-tests/tests/build/test-results/acceptanceTest/TEST-*.xml'
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@5f47764eec0e1c1f19f40c8e60a5ba47e47015c5
        if: (success() || failure()) # always run even if the build step fails
        with:
          report_paths: 'acceptance-tests/tests/build/test-results/acceptanceTest/TEST-*.xml'
  acceptance-tests:
    runs-on: ubuntu-22.04
    needs: [ acceptanceTestEthereum ]
    permissions:
      checks: write
      statuses: write
    steps:
      - name: consolidation
        run: echo "consolidating statuses"
