name: integration-tests
on:
  pull_request_target:

env:
  GRADLE_OPTS: "-Xmx6g -Dorg.gradle.daemon=false"

jobs:
  authorize:
    environment:
      ${{ github.event_name == 'pull_request_target' &&
      github.event.pull_request.head.repo.full_name != github.repository &&
      'external' || 'internal' }}
    runs-on: ubuntu-22.04
    steps:
      - run: true
  integration-tests:
    runs-on: ubuntu-22.04
    needs: authorize
    permissions:
      statuses: write
      checks: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
      - name: Set up Java
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93
        with:
          distribution: temurin
          java-version: 17
      - name: setup gradle
        uses: gradle/gradle-build-action@a8f75513eafdebd8141bd1cd4e30fcd194af8dfa
      - name: run integration tests
        run: ./gradlew integrationTest compileJmh -Dorg.gradle.parallel=true -Dorg.gradle.caching=true
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@5f47764eec0e1c1f19f40c8e60a5ba47e47015c5
        if: (success() || failure())
        with:
          report_paths: '**/build/test-results/integrationTest/TEST-*.xml'


